version: '3.8'

services:
  database:
    build:
      context: ./database
    container_name: comp_database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project1
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - custom_ipvlan

  backend:
    build:
      context: ./backend
    container_name: comp_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: project1
      DB_HOST: database
      DB_PORT: 5432
    depends_on:
      - database
    networks:
      - custom_ipvlan

volumes:
  db_data:
    # Use standard local driver to ensure volume persistence

networks:
  custom_ipvlan:
    external: true
