sonar.projectKey=sample-java-app
sonar.projectName=sample-java-app
sonar.projectVersion=1.0

sonar.sources=src

sonar.host.url=http://sonarqube:9000

sonar.login=sqa_d98f9bb43354da705d85ff511617c990b9253b0